server:
  port: 9092
  servlet.context-path: /dancing
  undertow.max-http-post-size: 0
  error:
    include-message: always
spring:
#  webflux.base-path: /dancing
  application.name: dancing
  main.allow-bean-definition-overriding: true
  jackson.default-property-inclusion: non_absent
  thymeleaf:
    cache: false
    check-template-location: true
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    template-resolver-order: 1
#  r2dbc:
#    url: r2dbc:mariadb://localhost:3308/sakila
#    username: root
#    password: 123456
#    pool:
#      enabled: false

datasource:
  mariadb:
    enabled: true
    host: localhost
    port: 3306
    database: sakila
    user: root
    password: 123456
    timeout: 10

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.web.FilterChainProxy: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.security: DEBUG
    org.springframework.boot.autoconfigure: INFO
#    org.springframework.r2dbc: TRACE
    org.springframework.r2dbc: DEBUG