server:
  port: 9092
  servlet.context-path: /dancing
  undertow.max-http-post-size: 0
  error:
    include-message: always
spring:
#  webflux.base-path: /dancing
  application.name: dancing
  main.allow-bean-definition-overriding: true
  jackson.default-property-inclusion: non_absent
  thymeleaf:
    cache: false
    check-template-location: true
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    template-resolver-order: 1
  jpa:
    #    show-sql: true
    properties:
      hibernate:
        format_sql: true
#        dialect: org.hibernate.dialect.MariaDB103Dialect
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        #        query:
        #          plan_cache_max_size: 1
        #          plan_parameter_metadata_max_size: 1
        #        generate_statistics: true
        jdbc:
          batch_size: 1000
          time_zone: UTC
        order_inserts: true
        order_updates: true
        use-new-id-generator-mappings: true
  datasource:
    url: jdbc:mysql://localhost:3308/sakila
    username: root
    password: 123456

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.web.FilterChainProxy: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.security: DEBUG
    org.springframework.boot.autoconfigure: INFO
    org.hibernate.SQL: DEBUG
    #    org.hibernate.type.descriptor.sql: trace
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE